import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Next_Practice",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (  
    <html lang="en">
      <body className="bg-gradient-to-r from-graycustom to-black">
          {children}
      </body>
    </html>
  );
}
